title: GBICi5-Scratch-1-BoatRace
hero_image: images/banner.png
description: GBICi5-Scratch-1-BoatRace description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-20"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
